import {
  PrismaClient,
  QuestCategory,
  BadgeRarity,
  BadgeTriggerEvent,
} from '@prisma/client';

export type BadgeSeedRow = {
  code: string;
  name: string;
  description: string;
  iconKey: string;
  category: QuestCategory;
  triggerEvent: BadgeTriggerEvent;
  threshold: number | null;
  conditionText: string;
  rarity: BadgeRarity;
};

export const BADGE_DEFINITIONS: BadgeSeedRow[] = [
  {
    code: 'first_trade',
    name: 'First Trade',
    description: 'Execute your first trade.',
    iconKey: '🎯',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.TRADE_EXECUTED,
    threshold: 1,
    conditionText: 'Execute your first trade.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'high_roller',
    name: 'High Roller',
    description: 'Execute 50 trades total.',
    iconKey: '🎲',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.TRADE_EXECUTED,
    threshold: 50,
    conditionText: 'Execute 50 trades in total.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'diversified',
    name: 'Diversified',
    description: 'Hold 5+ different stocks at once in one portfolio.',
    iconKey: '📊',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.TRADE_EXECUTED,
    threshold: 5,
    conditionText: 'Hold at least 5 different stocks at the same time.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'whale',
    name: 'Whale',
    description: 'Hold 10+ different stocks at once in one portfolio.',
    iconKey: '🐋',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.TRADE_EXECUTED,
    threshold: 10,
    conditionText: 'Hold at least 10 different stocks at the same time.',
    rarity: BadgeRarity.EPIC,
  },
  {
    code: 'quick_flip',
    name: 'Quick Flip',
    description: 'Buy and sell the same stock within 24 hours.',
    iconKey: '⚡',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.TRADE_EXECUTED,
    threshold: 1,
    conditionText: 'Sell a stock you bought in the last 24 hours (same portfolio).',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'league_creator',
    name: 'League Creator',
    description: 'Create a fantasy league.',
    iconKey: '🏟️',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_CREATED,
    threshold: 1,
    conditionText: 'Create a Bullring league.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'league_participant',
    name: 'League Participant',
    description: 'Complete any fantasy league.',
    iconKey: '🎟️',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 1,
    conditionText: 'Finish any league (ranked at the end).',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'top_3_finisher',
    name: 'Top 3 Finisher',
    description: 'Finish in the top 3 of any league.',
    iconKey: '🥉',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 3,
    conditionText: 'Place 1st, 2nd, or 3rd in a completed league.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'league_champion',
    name: 'League Champion',
    description: 'Finish 1st in any league.',
    iconKey: '👑',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 1,
    conditionText: 'Win 1st place in any completed league.',
    rarity: BadgeRarity.EPIC,
  },
  {
    code: 'undefeated',
    name: 'Undefeated',
    description: 'Win your last 3 completed leagues (1st place each).',
    iconKey: '🔥',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 3,
    conditionText: 'Place 1st in your three most recently completed leagues.',
    rarity: BadgeRarity.LEGENDARY,
  },
  {
    code: 'bull_run',
    name: 'Bull Run',
    description: 'Gain 20%+ on portfolio value in a single league.',
    iconKey: '📈',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 20,
    conditionText: 'End a league with ≥20% gain vs starting cash.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'comeback_kid',
    name: 'Comeback Kid',
    description: 'Win 1st after being last at the league midpoint.',
    iconKey: '🏆',
    category: QuestCategory.ACTION_STRATEGY,
    triggerEvent: BadgeTriggerEvent.LEAGUE_COMPLETED,
    threshold: 1,
    conditionText: 'Be last at the halfway snapshot, then finish 1st.',
    rarity: BadgeRarity.LEGENDARY,
  },
  {
    code: 'first_step',
    name: 'First Step',
    description: 'Complete your first quest.',
    iconKey: '👣',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.QUEST_COMPLETED,
    threshold: 1,
    conditionText: 'Claim your first quest reward.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'quest_hunter',
    name: 'Quest Hunter',
    description: 'Complete 10 quests total.',
    iconKey: '🗺️',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.QUEST_COMPLETED,
    threshold: 10,
    conditionText: 'Claim 10 quest rewards.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'scholar',
    name: 'Scholar',
    description: 'Read 10 educational articles.',
    iconKey: '📚',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.ARTICLE_READ,
    threshold: 10,
    conditionText: 'Mark 10 articles as read.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'quiz_passed',
    name: 'Quiz Passed',
    description: 'Pass your first quiz.',
    iconKey: '✅',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.QUIZ_PASSED,
    threshold: 1,
    conditionText: 'Pass any quiz.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'quiz_master',
    name: 'Quiz Master',
    description: 'Pass 5 different quizzes.',
    iconKey: '🎓',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.QUIZ_PASSED,
    threshold: 5,
    conditionText: 'Pass 5 unique quizzes.',
    rarity: BadgeRarity.RARE,
  },
  {
    code: 'perfect_score',
    name: 'Perfect Score',
    description: 'Score 100% on any quiz.',
    iconKey: '💯',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.QUIZ_PASSED,
    threshold: 100,
    conditionText: 'Get a perfect score on a quiz attempt.',
    rarity: BadgeRarity.EPIC,
  },
  {
    code: 'tier_up',
    name: 'Tier Up',
    description: 'Unlock a new trading tier.',
    iconKey: '⬆️',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.TIER_UPGRADED,
    threshold: 1,
    conditionText: 'Meet XP and quiz requirements for the next tier.',
    rarity: BadgeRarity.COMMON,
  },
  {
    code: 'elite_trader',
    name: 'Elite Trader',
    description: 'Reach the highest trading tier.',
    iconKey: '💎',
    category: QuestCategory.COMMUNITY_LEARNING,
    triggerEvent: BadgeTriggerEvent.TIER_UPGRADED,
    threshold: 1,
    conditionText: 'Reach the max tier configured for StockQuest.',
    rarity: BadgeRarity.LEGENDARY,
  },
];

export async function seedBadges(prisma: PrismaClient): Promise<number> {
  let n = 0;
  for (const b of BADGE_DEFINITIONS) {
    await prisma.badge.upsert({
      where: { code: b.code },
      create: {
        code: b.code,
        name: b.name,
        description: b.description,
        iconKey: b.iconKey,
        category: b.category,
        triggerEvent: b.triggerEvent,
        threshold: b.threshold,
        conditionText: b.conditionText,
        rarity: b.rarity,
      },
      update: {
        name: b.name,
        description: b.description,
        iconKey: b.iconKey,
        category: b.category,
        triggerEvent: b.triggerEvent,
        threshold: b.threshold,
        conditionText: b.conditionText,
        rarity: b.rarity,
      },
    });
    n++;
  }
  return n;
}
